### PR TITLE
🚧 Merge develop and master

### PR DESCRIPTION
**Pull request by dmihalcik-virtru**
I would like to delete the `develop` branch after this

### CODE REVIEW

**Review by pflynn-virtru — DISMISSED** [review]

**Comment by ivanovSPvirtru** [comment]
There was a bug on develop when you adding embedded `demo-example.txt` . Its easy to fix, console shows what is wrong, we should fix it before merge

**Comment by jrschumacher** [comment]
@ivanovSPvirtru not sure I follow but can you post how to reproduce and I can get to it today.

**Comment by dmihalcik-virtru** [comment]
I've fixed build (analytics crept back in due to the merge, after @biscoe916 removed them in #128) and the drag-and-drop as requested by @ivanovSPvirtru

**Comment by jrschumacher** [comment]
Do you need a review tonight?

**Comment by dmihalcik-virtru** [comment]
No rush; please feel free to wait until business hours. There are a lot of changed lines but most of the code should have been reviewed already. Mostly you'd be looking for bad auto-merge lines and the two post-merge commits to fix bugs introduced due to the separation of the branches

**Review by pflynn-virtru — APPROVED** [review]

**Comment by dmihalcik-virtru** [comment]
Paul is apparently not in the CODEOWNERS. :-/ So I'll still need your review @jrschumacher

**Review by jrschumacher — APPROVED** [review]
LGTM

**Pull request merged**
